(define (batch-hue pattern)
(let* ((filelist (cadr (file-glob pattern 1))))
(while (not (null? filelist))
    (let* ((filename (car filelist))
	(image (car (gimp-file-load RUN-NONINTERACTIVE filename filename)))
	(drawable (car (gimp-image-get-active-layer image))))
	(gimp-hue-saturation drawable 0 0 20 -60) 
    (gimp-file-save RUN-NONINTERACTIVE image drawable filename filename)
    (gimp-image-delete image))
    (set! filelist (cdr filelist)))))
